//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "CES_MEDICAMENTO_FK_ESTADO", "CES_ESTADO_MEDICAMENTO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BibliotecaMedicos.CES_ESTADO_MEDICAMENTO), "CES_MEDICAMENTO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BibliotecaMedicos.CES_MEDICAMENTO), true)]
[assembly: EdmRelationshipAttribute("Model", "CES_MEDICAMENTO_FK4", "CES_LABORATORIO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BibliotecaMedicos.CES_LABORATORIO), "CES_MEDICAMENTO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BibliotecaMedicos.CES_MEDICAMENTO), true)]
[assembly: EdmRelationshipAttribute("Model", "CES_MEDICAMENTO_FK_ADM", "CES_TIPO_ADMIN_MED", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BibliotecaMedicos.CES_TIPO_ADMIN_MED), "CES_MEDICAMENTO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BibliotecaMedicos.CES_MEDICAMENTO), true)]
[assembly: EdmRelationshipAttribute("Model", "CES_MEDICAMENTO_FK_TIPO_MED", "CES_TIPO_MEDICAMENTO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BibliotecaMedicos.CES_TIPO_MEDICAMENTO), "CES_MEDICAMENTO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BibliotecaMedicos.CES_MEDICAMENTO), true)]
[assembly: EdmRelationshipAttribute("Model", "CES_USUARIO_FK_PER", "CES_PERSONA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BibliotecaMedicos.CES_PERSONA), "CES_USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BibliotecaMedicos.CES_USUARIO), true)]
[assembly: EdmRelationshipAttribute("Model", "CES_USUARIO_FK_TIPO_USU", "CES_TIPO_USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BibliotecaMedicos.CES_TIPO_USUARIO), "CES_USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BibliotecaMedicos.CES_USUARIO), true)]

#endregion

namespace BibliotecaMedicos
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class farmaciaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new farmaciaEntities object using the connection string found in the 'farmaciaEntities' section of the application configuration file.
        /// </summary>
        public farmaciaEntities() : base("name=farmaciaEntities", "farmaciaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new farmaciaEntities object.
        /// </summary>
        public farmaciaEntities(string connectionString) : base(connectionString, "farmaciaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new farmaciaEntities object.
        /// </summary>
        public farmaciaEntities(EntityConnection connection) : base(connection, "farmaciaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CES_ERRORES> CES_ERRORES
        {
            get
            {
                if ((_CES_ERRORES == null))
                {
                    _CES_ERRORES = base.CreateObjectSet<CES_ERRORES>("CES_ERRORES");
                }
                return _CES_ERRORES;
            }
        }
        private ObjectSet<CES_ERRORES> _CES_ERRORES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CES_ESTADO_MEDICAMENTO> CES_ESTADO_MEDICAMENTO
        {
            get
            {
                if ((_CES_ESTADO_MEDICAMENTO == null))
                {
                    _CES_ESTADO_MEDICAMENTO = base.CreateObjectSet<CES_ESTADO_MEDICAMENTO>("CES_ESTADO_MEDICAMENTO");
                }
                return _CES_ESTADO_MEDICAMENTO;
            }
        }
        private ObjectSet<CES_ESTADO_MEDICAMENTO> _CES_ESTADO_MEDICAMENTO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CES_LABORATORIO> CES_LABORATORIO
        {
            get
            {
                if ((_CES_LABORATORIO == null))
                {
                    _CES_LABORATORIO = base.CreateObjectSet<CES_LABORATORIO>("CES_LABORATORIO");
                }
                return _CES_LABORATORIO;
            }
        }
        private ObjectSet<CES_LABORATORIO> _CES_LABORATORIO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CES_MEDICAMENTO> CES_MEDICAMENTO
        {
            get
            {
                if ((_CES_MEDICAMENTO == null))
                {
                    _CES_MEDICAMENTO = base.CreateObjectSet<CES_MEDICAMENTO>("CES_MEDICAMENTO");
                }
                return _CES_MEDICAMENTO;
            }
        }
        private ObjectSet<CES_MEDICAMENTO> _CES_MEDICAMENTO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CES_PERSONA> CES_PERSONA
        {
            get
            {
                if ((_CES_PERSONA == null))
                {
                    _CES_PERSONA = base.CreateObjectSet<CES_PERSONA>("CES_PERSONA");
                }
                return _CES_PERSONA;
            }
        }
        private ObjectSet<CES_PERSONA> _CES_PERSONA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CES_TIPO_ADMIN_MED> CES_TIPO_ADMIN_MED
        {
            get
            {
                if ((_CES_TIPO_ADMIN_MED == null))
                {
                    _CES_TIPO_ADMIN_MED = base.CreateObjectSet<CES_TIPO_ADMIN_MED>("CES_TIPO_ADMIN_MED");
                }
                return _CES_TIPO_ADMIN_MED;
            }
        }
        private ObjectSet<CES_TIPO_ADMIN_MED> _CES_TIPO_ADMIN_MED;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CES_TIPO_MEDICAMENTO> CES_TIPO_MEDICAMENTO
        {
            get
            {
                if ((_CES_TIPO_MEDICAMENTO == null))
                {
                    _CES_TIPO_MEDICAMENTO = base.CreateObjectSet<CES_TIPO_MEDICAMENTO>("CES_TIPO_MEDICAMENTO");
                }
                return _CES_TIPO_MEDICAMENTO;
            }
        }
        private ObjectSet<CES_TIPO_MEDICAMENTO> _CES_TIPO_MEDICAMENTO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CES_TIPO_USUARIO> CES_TIPO_USUARIO
        {
            get
            {
                if ((_CES_TIPO_USUARIO == null))
                {
                    _CES_TIPO_USUARIO = base.CreateObjectSet<CES_TIPO_USUARIO>("CES_TIPO_USUARIO");
                }
                return _CES_TIPO_USUARIO;
            }
        }
        private ObjectSet<CES_TIPO_USUARIO> _CES_TIPO_USUARIO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CES_USUARIO> CES_USUARIO
        {
            get
            {
                if ((_CES_USUARIO == null))
                {
                    _CES_USUARIO = base.CreateObjectSet<CES_USUARIO>("CES_USUARIO");
                }
                return _CES_USUARIO;
            }
        }
        private ObjectSet<CES_USUARIO> _CES_USUARIO;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CES_ERRORES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCES_ERRORES(CES_ERRORES cES_ERRORES)
        {
            base.AddObject("CES_ERRORES", cES_ERRORES);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CES_ESTADO_MEDICAMENTO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCES_ESTADO_MEDICAMENTO(CES_ESTADO_MEDICAMENTO cES_ESTADO_MEDICAMENTO)
        {
            base.AddObject("CES_ESTADO_MEDICAMENTO", cES_ESTADO_MEDICAMENTO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CES_LABORATORIO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCES_LABORATORIO(CES_LABORATORIO cES_LABORATORIO)
        {
            base.AddObject("CES_LABORATORIO", cES_LABORATORIO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CES_MEDICAMENTO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCES_MEDICAMENTO(CES_MEDICAMENTO cES_MEDICAMENTO)
        {
            base.AddObject("CES_MEDICAMENTO", cES_MEDICAMENTO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CES_PERSONA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCES_PERSONA(CES_PERSONA cES_PERSONA)
        {
            base.AddObject("CES_PERSONA", cES_PERSONA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CES_TIPO_ADMIN_MED EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCES_TIPO_ADMIN_MED(CES_TIPO_ADMIN_MED cES_TIPO_ADMIN_MED)
        {
            base.AddObject("CES_TIPO_ADMIN_MED", cES_TIPO_ADMIN_MED);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CES_TIPO_MEDICAMENTO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCES_TIPO_MEDICAMENTO(CES_TIPO_MEDICAMENTO cES_TIPO_MEDICAMENTO)
        {
            base.AddObject("CES_TIPO_MEDICAMENTO", cES_TIPO_MEDICAMENTO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CES_TIPO_USUARIO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCES_TIPO_USUARIO(CES_TIPO_USUARIO cES_TIPO_USUARIO)
        {
            base.AddObject("CES_TIPO_USUARIO", cES_TIPO_USUARIO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CES_USUARIO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCES_USUARIO(CES_USUARIO cES_USUARIO)
        {
            base.AddObject("CES_USUARIO", cES_USUARIO);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CES_ERRORES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CES_ERRORES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CES_ERRORES object.
        /// </summary>
        /// <param name="eRR_ID">Initial value of the ERR_ID property.</param>
        /// <param name="eRR_NUM_ERROR">Initial value of the ERR_NUM_ERROR property.</param>
        /// <param name="eRR_DESCRIPCION_ERROR">Initial value of the ERR_DESCRIPCION_ERROR property.</param>
        /// <param name="eRR_VIGENCIA">Initial value of the ERR_VIGENCIA property.</param>
        public static CES_ERRORES CreateCES_ERRORES(global::System.Int32 eRR_ID, global::System.Int32 eRR_NUM_ERROR, global::System.String eRR_DESCRIPCION_ERROR, global::System.String eRR_VIGENCIA)
        {
            CES_ERRORES cES_ERRORES = new CES_ERRORES();
            cES_ERRORES.ERR_ID = eRR_ID;
            cES_ERRORES.ERR_NUM_ERROR = eRR_NUM_ERROR;
            cES_ERRORES.ERR_DESCRIPCION_ERROR = eRR_DESCRIPCION_ERROR;
            cES_ERRORES.ERR_VIGENCIA = eRR_VIGENCIA;
            return cES_ERRORES;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ERR_ID
        {
            get
            {
                return _ERR_ID;
            }
            set
            {
                if (_ERR_ID != value)
                {
                    OnERR_IDChanging(value);
                    ReportPropertyChanging("ERR_ID");
                    _ERR_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ERR_ID");
                    OnERR_IDChanged();
                }
            }
        }
        private global::System.Int32 _ERR_ID;
        partial void OnERR_IDChanging(global::System.Int32 value);
        partial void OnERR_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ERR_NUM_ERROR
        {
            get
            {
                return _ERR_NUM_ERROR;
            }
            set
            {
                OnERR_NUM_ERRORChanging(value);
                ReportPropertyChanging("ERR_NUM_ERROR");
                _ERR_NUM_ERROR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ERR_NUM_ERROR");
                OnERR_NUM_ERRORChanged();
            }
        }
        private global::System.Int32 _ERR_NUM_ERROR;
        partial void OnERR_NUM_ERRORChanging(global::System.Int32 value);
        partial void OnERR_NUM_ERRORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ERR_DESCRIPCION_ERROR
        {
            get
            {
                return _ERR_DESCRIPCION_ERROR;
            }
            set
            {
                OnERR_DESCRIPCION_ERRORChanging(value);
                ReportPropertyChanging("ERR_DESCRIPCION_ERROR");
                _ERR_DESCRIPCION_ERROR = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ERR_DESCRIPCION_ERROR");
                OnERR_DESCRIPCION_ERRORChanged();
            }
        }
        private global::System.String _ERR_DESCRIPCION_ERROR;
        partial void OnERR_DESCRIPCION_ERRORChanging(global::System.String value);
        partial void OnERR_DESCRIPCION_ERRORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ERR_VIGENCIA
        {
            get
            {
                return _ERR_VIGENCIA;
            }
            set
            {
                OnERR_VIGENCIAChanging(value);
                ReportPropertyChanging("ERR_VIGENCIA");
                _ERR_VIGENCIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ERR_VIGENCIA");
                OnERR_VIGENCIAChanged();
            }
        }
        private global::System.String _ERR_VIGENCIA;
        partial void OnERR_VIGENCIAChanging(global::System.String value);
        partial void OnERR_VIGENCIAChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CES_ESTADO_MEDICAMENTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CES_ESTADO_MEDICAMENTO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CES_ESTADO_MEDICAMENTO object.
        /// </summary>
        /// <param name="eST_ID">Initial value of the EST_ID property.</param>
        /// <param name="eST_DESCRIPCION">Initial value of the EST_DESCRIPCION property.</param>
        /// <param name="eST_VIGENCIA">Initial value of the EST_VIGENCIA property.</param>
        public static CES_ESTADO_MEDICAMENTO CreateCES_ESTADO_MEDICAMENTO(global::System.Int16 eST_ID, global::System.String eST_DESCRIPCION, global::System.String eST_VIGENCIA)
        {
            CES_ESTADO_MEDICAMENTO cES_ESTADO_MEDICAMENTO = new CES_ESTADO_MEDICAMENTO();
            cES_ESTADO_MEDICAMENTO.EST_ID = eST_ID;
            cES_ESTADO_MEDICAMENTO.EST_DESCRIPCION = eST_DESCRIPCION;
            cES_ESTADO_MEDICAMENTO.EST_VIGENCIA = eST_VIGENCIA;
            return cES_ESTADO_MEDICAMENTO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 EST_ID
        {
            get
            {
                return _EST_ID;
            }
            set
            {
                if (_EST_ID != value)
                {
                    OnEST_IDChanging(value);
                    ReportPropertyChanging("EST_ID");
                    _EST_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EST_ID");
                    OnEST_IDChanged();
                }
            }
        }
        private global::System.Int16 _EST_ID;
        partial void OnEST_IDChanging(global::System.Int16 value);
        partial void OnEST_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EST_DESCRIPCION
        {
            get
            {
                return _EST_DESCRIPCION;
            }
            set
            {
                OnEST_DESCRIPCIONChanging(value);
                ReportPropertyChanging("EST_DESCRIPCION");
                _EST_DESCRIPCION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EST_DESCRIPCION");
                OnEST_DESCRIPCIONChanged();
            }
        }
        private global::System.String _EST_DESCRIPCION;
        partial void OnEST_DESCRIPCIONChanging(global::System.String value);
        partial void OnEST_DESCRIPCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EST_VIGENCIA
        {
            get
            {
                return _EST_VIGENCIA;
            }
            set
            {
                OnEST_VIGENCIAChanging(value);
                ReportPropertyChanging("EST_VIGENCIA");
                _EST_VIGENCIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EST_VIGENCIA");
                OnEST_VIGENCIAChanged();
            }
        }
        private global::System.String _EST_VIGENCIA;
        partial void OnEST_VIGENCIAChanging(global::System.String value);
        partial void OnEST_VIGENCIAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CES_MEDICAMENTO_FK_ESTADO", "CES_MEDICAMENTO")]
        public EntityCollection<CES_MEDICAMENTO> CES_MEDICAMENTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CES_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_ESTADO", "CES_MEDICAMENTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CES_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_ESTADO", "CES_MEDICAMENTO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CES_LABORATORIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CES_LABORATORIO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CES_LABORATORIO object.
        /// </summary>
        /// <param name="lAB_ID">Initial value of the LAB_ID property.</param>
        /// <param name="lAB_DESCRIPCION">Initial value of the LAB_DESCRIPCION property.</param>
        /// <param name="lAB_VIGENCIA">Initial value of the LAB_VIGENCIA property.</param>
        public static CES_LABORATORIO CreateCES_LABORATORIO(global::System.Int16 lAB_ID, global::System.String lAB_DESCRIPCION, global::System.String lAB_VIGENCIA)
        {
            CES_LABORATORIO cES_LABORATORIO = new CES_LABORATORIO();
            cES_LABORATORIO.LAB_ID = lAB_ID;
            cES_LABORATORIO.LAB_DESCRIPCION = lAB_DESCRIPCION;
            cES_LABORATORIO.LAB_VIGENCIA = lAB_VIGENCIA;
            return cES_LABORATORIO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 LAB_ID
        {
            get
            {
                return _LAB_ID;
            }
            set
            {
                if (_LAB_ID != value)
                {
                    OnLAB_IDChanging(value);
                    ReportPropertyChanging("LAB_ID");
                    _LAB_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LAB_ID");
                    OnLAB_IDChanged();
                }
            }
        }
        private global::System.Int16 _LAB_ID;
        partial void OnLAB_IDChanging(global::System.Int16 value);
        partial void OnLAB_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LAB_DESCRIPCION
        {
            get
            {
                return _LAB_DESCRIPCION;
            }
            set
            {
                OnLAB_DESCRIPCIONChanging(value);
                ReportPropertyChanging("LAB_DESCRIPCION");
                _LAB_DESCRIPCION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LAB_DESCRIPCION");
                OnLAB_DESCRIPCIONChanged();
            }
        }
        private global::System.String _LAB_DESCRIPCION;
        partial void OnLAB_DESCRIPCIONChanging(global::System.String value);
        partial void OnLAB_DESCRIPCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LAB_VIGENCIA
        {
            get
            {
                return _LAB_VIGENCIA;
            }
            set
            {
                OnLAB_VIGENCIAChanging(value);
                ReportPropertyChanging("LAB_VIGENCIA");
                _LAB_VIGENCIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LAB_VIGENCIA");
                OnLAB_VIGENCIAChanged();
            }
        }
        private global::System.String _LAB_VIGENCIA;
        partial void OnLAB_VIGENCIAChanging(global::System.String value);
        partial void OnLAB_VIGENCIAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CES_MEDICAMENTO_FK4", "CES_MEDICAMENTO")]
        public EntityCollection<CES_MEDICAMENTO> CES_MEDICAMENTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CES_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK4", "CES_MEDICAMENTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CES_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK4", "CES_MEDICAMENTO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CES_MEDICAMENTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CES_MEDICAMENTO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CES_MEDICAMENTO object.
        /// </summary>
        /// <param name="mED_ID">Initial value of the MED_ID property.</param>
        /// <param name="mED_NOMBRE">Initial value of the MED_NOMBRE property.</param>
        /// <param name="mED_FECHA_ELABORACION">Initial value of the MED_FECHA_ELABORACION property.</param>
        /// <param name="mED_FECHA_VENCIMIENTO">Initial value of the MED_FECHA_VENCIMIENTO property.</param>
        /// <param name="mED_VIGENCIA">Initial value of the MED_VIGENCIA property.</param>
        /// <param name="eST_ID">Initial value of the EST_ID property.</param>
        /// <param name="tIPO_MED_ID">Initial value of the TIPO_MED_ID property.</param>
        /// <param name="tIPO_ADM_ID">Initial value of the TIPO_ADM_ID property.</param>
        /// <param name="mED_STOCK">Initial value of the MED_STOCK property.</param>
        /// <param name="mED_RESERVADO">Initial value of the MED_RESERVADO property.</param>
        /// <param name="lAB_ID">Initial value of the LAB_ID property.</param>
        public static CES_MEDICAMENTO CreateCES_MEDICAMENTO(global::System.Int32 mED_ID, global::System.String mED_NOMBRE, global::System.DateTime mED_FECHA_ELABORACION, global::System.DateTime mED_FECHA_VENCIMIENTO, global::System.String mED_VIGENCIA, global::System.Int16 eST_ID, global::System.Int16 tIPO_MED_ID, global::System.Int16 tIPO_ADM_ID, global::System.Int32 mED_STOCK, global::System.String mED_RESERVADO, global::System.Int16 lAB_ID)
        {
            CES_MEDICAMENTO cES_MEDICAMENTO = new CES_MEDICAMENTO();
            cES_MEDICAMENTO.MED_ID = mED_ID;
            cES_MEDICAMENTO.MED_NOMBRE = mED_NOMBRE;
            cES_MEDICAMENTO.MED_FECHA_ELABORACION = mED_FECHA_ELABORACION;
            cES_MEDICAMENTO.MED_FECHA_VENCIMIENTO = mED_FECHA_VENCIMIENTO;
            cES_MEDICAMENTO.MED_VIGENCIA = mED_VIGENCIA;
            cES_MEDICAMENTO.EST_ID = eST_ID;
            cES_MEDICAMENTO.TIPO_MED_ID = tIPO_MED_ID;
            cES_MEDICAMENTO.TIPO_ADM_ID = tIPO_ADM_ID;
            cES_MEDICAMENTO.MED_STOCK = mED_STOCK;
            cES_MEDICAMENTO.MED_RESERVADO = mED_RESERVADO;
            cES_MEDICAMENTO.LAB_ID = lAB_ID;
            return cES_MEDICAMENTO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MED_ID
        {
            get
            {
                return _MED_ID;
            }
            set
            {
                if (_MED_ID != value)
                {
                    OnMED_IDChanging(value);
                    ReportPropertyChanging("MED_ID");
                    _MED_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MED_ID");
                    OnMED_IDChanged();
                }
            }
        }
        private global::System.Int32 _MED_ID;
        partial void OnMED_IDChanging(global::System.Int32 value);
        partial void OnMED_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MED_NOMBRE
        {
            get
            {
                return _MED_NOMBRE;
            }
            set
            {
                OnMED_NOMBREChanging(value);
                ReportPropertyChanging("MED_NOMBRE");
                _MED_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MED_NOMBRE");
                OnMED_NOMBREChanged();
            }
        }
        private global::System.String _MED_NOMBRE;
        partial void OnMED_NOMBREChanging(global::System.String value);
        partial void OnMED_NOMBREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MED_FECHA_ELABORACION
        {
            get
            {
                return _MED_FECHA_ELABORACION;
            }
            set
            {
                OnMED_FECHA_ELABORACIONChanging(value);
                ReportPropertyChanging("MED_FECHA_ELABORACION");
                _MED_FECHA_ELABORACION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MED_FECHA_ELABORACION");
                OnMED_FECHA_ELABORACIONChanged();
            }
        }
        private global::System.DateTime _MED_FECHA_ELABORACION;
        partial void OnMED_FECHA_ELABORACIONChanging(global::System.DateTime value);
        partial void OnMED_FECHA_ELABORACIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MED_FECHA_VENCIMIENTO
        {
            get
            {
                return _MED_FECHA_VENCIMIENTO;
            }
            set
            {
                OnMED_FECHA_VENCIMIENTOChanging(value);
                ReportPropertyChanging("MED_FECHA_VENCIMIENTO");
                _MED_FECHA_VENCIMIENTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MED_FECHA_VENCIMIENTO");
                OnMED_FECHA_VENCIMIENTOChanged();
            }
        }
        private global::System.DateTime _MED_FECHA_VENCIMIENTO;
        partial void OnMED_FECHA_VENCIMIENTOChanging(global::System.DateTime value);
        partial void OnMED_FECHA_VENCIMIENTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MED_COMENTARIOS
        {
            get
            {
                return _MED_COMENTARIOS;
            }
            set
            {
                OnMED_COMENTARIOSChanging(value);
                ReportPropertyChanging("MED_COMENTARIOS");
                _MED_COMENTARIOS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MED_COMENTARIOS");
                OnMED_COMENTARIOSChanged();
            }
        }
        private global::System.String _MED_COMENTARIOS;
        partial void OnMED_COMENTARIOSChanging(global::System.String value);
        partial void OnMED_COMENTARIOSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MED_VIGENCIA
        {
            get
            {
                return _MED_VIGENCIA;
            }
            set
            {
                OnMED_VIGENCIAChanging(value);
                ReportPropertyChanging("MED_VIGENCIA");
                _MED_VIGENCIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MED_VIGENCIA");
                OnMED_VIGENCIAChanged();
            }
        }
        private global::System.String _MED_VIGENCIA;
        partial void OnMED_VIGENCIAChanging(global::System.String value);
        partial void OnMED_VIGENCIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 EST_ID
        {
            get
            {
                return _EST_ID;
            }
            set
            {
                OnEST_IDChanging(value);
                ReportPropertyChanging("EST_ID");
                _EST_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EST_ID");
                OnEST_IDChanged();
            }
        }
        private global::System.Int16 _EST_ID;
        partial void OnEST_IDChanging(global::System.Int16 value);
        partial void OnEST_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TIPO_MED_ID
        {
            get
            {
                return _TIPO_MED_ID;
            }
            set
            {
                OnTIPO_MED_IDChanging(value);
                ReportPropertyChanging("TIPO_MED_ID");
                _TIPO_MED_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TIPO_MED_ID");
                OnTIPO_MED_IDChanged();
            }
        }
        private global::System.Int16 _TIPO_MED_ID;
        partial void OnTIPO_MED_IDChanging(global::System.Int16 value);
        partial void OnTIPO_MED_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TIPO_ADM_ID
        {
            get
            {
                return _TIPO_ADM_ID;
            }
            set
            {
                OnTIPO_ADM_IDChanging(value);
                ReportPropertyChanging("TIPO_ADM_ID");
                _TIPO_ADM_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TIPO_ADM_ID");
                OnTIPO_ADM_IDChanged();
            }
        }
        private global::System.Int16 _TIPO_ADM_ID;
        partial void OnTIPO_ADM_IDChanging(global::System.Int16 value);
        partial void OnTIPO_ADM_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MED_STOCK
        {
            get
            {
                return _MED_STOCK;
            }
            set
            {
                OnMED_STOCKChanging(value);
                ReportPropertyChanging("MED_STOCK");
                _MED_STOCK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MED_STOCK");
                OnMED_STOCKChanged();
            }
        }
        private global::System.Int32 _MED_STOCK;
        partial void OnMED_STOCKChanging(global::System.Int32 value);
        partial void OnMED_STOCKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MED_RESERVADO
        {
            get
            {
                return _MED_RESERVADO;
            }
            set
            {
                OnMED_RESERVADOChanging(value);
                ReportPropertyChanging("MED_RESERVADO");
                _MED_RESERVADO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MED_RESERVADO");
                OnMED_RESERVADOChanged();
            }
        }
        private global::System.String _MED_RESERVADO;
        partial void OnMED_RESERVADOChanging(global::System.String value);
        partial void OnMED_RESERVADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MED_FECHA_INGRESO
        {
            get
            {
                return _MED_FECHA_INGRESO;
            }
            set
            {
                OnMED_FECHA_INGRESOChanging(value);
                ReportPropertyChanging("MED_FECHA_INGRESO");
                _MED_FECHA_INGRESO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MED_FECHA_INGRESO");
                OnMED_FECHA_INGRESOChanged();
            }
        }
        private Nullable<global::System.DateTime> _MED_FECHA_INGRESO;
        partial void OnMED_FECHA_INGRESOChanging(Nullable<global::System.DateTime> value);
        partial void OnMED_FECHA_INGRESOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 LAB_ID
        {
            get
            {
                return _LAB_ID;
            }
            set
            {
                OnLAB_IDChanging(value);
                ReportPropertyChanging("LAB_ID");
                _LAB_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LAB_ID");
                OnLAB_IDChanged();
            }
        }
        private global::System.Int16 _LAB_ID;
        partial void OnLAB_IDChanging(global::System.Int16 value);
        partial void OnLAB_IDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CES_MEDICAMENTO_FK_ESTADO", "CES_ESTADO_MEDICAMENTO")]
        public CES_ESTADO_MEDICAMENTO CES_ESTADO_MEDICAMENTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_ESTADO_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_ESTADO", "CES_ESTADO_MEDICAMENTO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_ESTADO_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_ESTADO", "CES_ESTADO_MEDICAMENTO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CES_ESTADO_MEDICAMENTO> CES_ESTADO_MEDICAMENTOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_ESTADO_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_ESTADO", "CES_ESTADO_MEDICAMENTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CES_ESTADO_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_ESTADO", "CES_ESTADO_MEDICAMENTO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CES_MEDICAMENTO_FK4", "CES_LABORATORIO")]
        public CES_LABORATORIO CES_LABORATORIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_LABORATORIO>("Model.CES_MEDICAMENTO_FK4", "CES_LABORATORIO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_LABORATORIO>("Model.CES_MEDICAMENTO_FK4", "CES_LABORATORIO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CES_LABORATORIO> CES_LABORATORIOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_LABORATORIO>("Model.CES_MEDICAMENTO_FK4", "CES_LABORATORIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CES_LABORATORIO>("Model.CES_MEDICAMENTO_FK4", "CES_LABORATORIO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CES_MEDICAMENTO_FK_ADM", "CES_TIPO_ADMIN_MED")]
        public CES_TIPO_ADMIN_MED CES_TIPO_ADMIN_MED
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_TIPO_ADMIN_MED>("Model.CES_MEDICAMENTO_FK_ADM", "CES_TIPO_ADMIN_MED").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_TIPO_ADMIN_MED>("Model.CES_MEDICAMENTO_FK_ADM", "CES_TIPO_ADMIN_MED").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CES_TIPO_ADMIN_MED> CES_TIPO_ADMIN_MEDReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_TIPO_ADMIN_MED>("Model.CES_MEDICAMENTO_FK_ADM", "CES_TIPO_ADMIN_MED");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CES_TIPO_ADMIN_MED>("Model.CES_MEDICAMENTO_FK_ADM", "CES_TIPO_ADMIN_MED", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CES_MEDICAMENTO_FK_TIPO_MED", "CES_TIPO_MEDICAMENTO")]
        public CES_TIPO_MEDICAMENTO CES_TIPO_MEDICAMENTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_TIPO_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_TIPO_MED", "CES_TIPO_MEDICAMENTO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_TIPO_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_TIPO_MED", "CES_TIPO_MEDICAMENTO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CES_TIPO_MEDICAMENTO> CES_TIPO_MEDICAMENTOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_TIPO_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_TIPO_MED", "CES_TIPO_MEDICAMENTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CES_TIPO_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_TIPO_MED", "CES_TIPO_MEDICAMENTO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CES_PERSONA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CES_PERSONA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CES_PERSONA object.
        /// </summary>
        /// <param name="pER_RUT">Initial value of the PER_RUT property.</param>
        /// <param name="pER_DV">Initial value of the PER_DV property.</param>
        /// <param name="pER_NOMBRES">Initial value of the PER_NOMBRES property.</param>
        /// <param name="pER_APELLIDO_PATERNO">Initial value of the PER_APELLIDO_PATERNO property.</param>
        /// <param name="pER_APELLIDO_MATERNO">Initial value of the PER_APELLIDO_MATERNO property.</param>
        /// <param name="pER_SEXO">Initial value of the PER_SEXO property.</param>
        /// <param name="pER_FECHA_NACIMIENTO">Initial value of the PER_FECHA_NACIMIENTO property.</param>
        /// <param name="pER_TELEFONO">Initial value of the PER_TELEFONO property.</param>
        /// <param name="pER_VIGENCIA">Initial value of the PER_VIGENCIA property.</param>
        public static CES_PERSONA CreateCES_PERSONA(global::System.Int32 pER_RUT, global::System.String pER_DV, global::System.String pER_NOMBRES, global::System.String pER_APELLIDO_PATERNO, global::System.String pER_APELLIDO_MATERNO, global::System.String pER_SEXO, global::System.DateTime pER_FECHA_NACIMIENTO, global::System.Int32 pER_TELEFONO, global::System.String pER_VIGENCIA)
        {
            CES_PERSONA cES_PERSONA = new CES_PERSONA();
            cES_PERSONA.PER_RUT = pER_RUT;
            cES_PERSONA.PER_DV = pER_DV;
            cES_PERSONA.PER_NOMBRES = pER_NOMBRES;
            cES_PERSONA.PER_APELLIDO_PATERNO = pER_APELLIDO_PATERNO;
            cES_PERSONA.PER_APELLIDO_MATERNO = pER_APELLIDO_MATERNO;
            cES_PERSONA.PER_SEXO = pER_SEXO;
            cES_PERSONA.PER_FECHA_NACIMIENTO = pER_FECHA_NACIMIENTO;
            cES_PERSONA.PER_TELEFONO = pER_TELEFONO;
            cES_PERSONA.PER_VIGENCIA = pER_VIGENCIA;
            return cES_PERSONA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PER_RUT
        {
            get
            {
                return _PER_RUT;
            }
            set
            {
                if (_PER_RUT != value)
                {
                    OnPER_RUTChanging(value);
                    ReportPropertyChanging("PER_RUT");
                    _PER_RUT = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PER_RUT");
                    OnPER_RUTChanged();
                }
            }
        }
        private global::System.Int32 _PER_RUT;
        partial void OnPER_RUTChanging(global::System.Int32 value);
        partial void OnPER_RUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PER_DV
        {
            get
            {
                return _PER_DV;
            }
            set
            {
                OnPER_DVChanging(value);
                ReportPropertyChanging("PER_DV");
                _PER_DV = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PER_DV");
                OnPER_DVChanged();
            }
        }
        private global::System.String _PER_DV;
        partial void OnPER_DVChanging(global::System.String value);
        partial void OnPER_DVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PER_NOMBRES
        {
            get
            {
                return _PER_NOMBRES;
            }
            set
            {
                OnPER_NOMBRESChanging(value);
                ReportPropertyChanging("PER_NOMBRES");
                _PER_NOMBRES = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PER_NOMBRES");
                OnPER_NOMBRESChanged();
            }
        }
        private global::System.String _PER_NOMBRES;
        partial void OnPER_NOMBRESChanging(global::System.String value);
        partial void OnPER_NOMBRESChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PER_APELLIDO_PATERNO
        {
            get
            {
                return _PER_APELLIDO_PATERNO;
            }
            set
            {
                OnPER_APELLIDO_PATERNOChanging(value);
                ReportPropertyChanging("PER_APELLIDO_PATERNO");
                _PER_APELLIDO_PATERNO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PER_APELLIDO_PATERNO");
                OnPER_APELLIDO_PATERNOChanged();
            }
        }
        private global::System.String _PER_APELLIDO_PATERNO;
        partial void OnPER_APELLIDO_PATERNOChanging(global::System.String value);
        partial void OnPER_APELLIDO_PATERNOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PER_APELLIDO_MATERNO
        {
            get
            {
                return _PER_APELLIDO_MATERNO;
            }
            set
            {
                OnPER_APELLIDO_MATERNOChanging(value);
                ReportPropertyChanging("PER_APELLIDO_MATERNO");
                _PER_APELLIDO_MATERNO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PER_APELLIDO_MATERNO");
                OnPER_APELLIDO_MATERNOChanged();
            }
        }
        private global::System.String _PER_APELLIDO_MATERNO;
        partial void OnPER_APELLIDO_MATERNOChanging(global::System.String value);
        partial void OnPER_APELLIDO_MATERNOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PER_NOMBRE_COMPLETO
        {
            get
            {
                return _PER_NOMBRE_COMPLETO;
            }
            set
            {
                OnPER_NOMBRE_COMPLETOChanging(value);
                ReportPropertyChanging("PER_NOMBRE_COMPLETO");
                _PER_NOMBRE_COMPLETO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PER_NOMBRE_COMPLETO");
                OnPER_NOMBRE_COMPLETOChanged();
            }
        }
        private global::System.String _PER_NOMBRE_COMPLETO;
        partial void OnPER_NOMBRE_COMPLETOChanging(global::System.String value);
        partial void OnPER_NOMBRE_COMPLETOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PER_SEXO
        {
            get
            {
                return _PER_SEXO;
            }
            set
            {
                OnPER_SEXOChanging(value);
                ReportPropertyChanging("PER_SEXO");
                _PER_SEXO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PER_SEXO");
                OnPER_SEXOChanged();
            }
        }
        private global::System.String _PER_SEXO;
        partial void OnPER_SEXOChanging(global::System.String value);
        partial void OnPER_SEXOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PER_FECHA_NACIMIENTO
        {
            get
            {
                return _PER_FECHA_NACIMIENTO;
            }
            set
            {
                OnPER_FECHA_NACIMIENTOChanging(value);
                ReportPropertyChanging("PER_FECHA_NACIMIENTO");
                _PER_FECHA_NACIMIENTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PER_FECHA_NACIMIENTO");
                OnPER_FECHA_NACIMIENTOChanged();
            }
        }
        private global::System.DateTime _PER_FECHA_NACIMIENTO;
        partial void OnPER_FECHA_NACIMIENTOChanging(global::System.DateTime value);
        partial void OnPER_FECHA_NACIMIENTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PER_FECHA_REGISTRO
        {
            get
            {
                return _PER_FECHA_REGISTRO;
            }
            set
            {
                OnPER_FECHA_REGISTROChanging(value);
                ReportPropertyChanging("PER_FECHA_REGISTRO");
                _PER_FECHA_REGISTRO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PER_FECHA_REGISTRO");
                OnPER_FECHA_REGISTROChanged();
            }
        }
        private Nullable<global::System.DateTime> _PER_FECHA_REGISTRO;
        partial void OnPER_FECHA_REGISTROChanging(Nullable<global::System.DateTime> value);
        partial void OnPER_FECHA_REGISTROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PER_TELEFONO
        {
            get
            {
                return _PER_TELEFONO;
            }
            set
            {
                OnPER_TELEFONOChanging(value);
                ReportPropertyChanging("PER_TELEFONO");
                _PER_TELEFONO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PER_TELEFONO");
                OnPER_TELEFONOChanged();
            }
        }
        private global::System.Int32 _PER_TELEFONO;
        partial void OnPER_TELEFONOChanging(global::System.Int32 value);
        partial void OnPER_TELEFONOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PER_EMAIL
        {
            get
            {
                return _PER_EMAIL;
            }
            set
            {
                OnPER_EMAILChanging(value);
                ReportPropertyChanging("PER_EMAIL");
                _PER_EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PER_EMAIL");
                OnPER_EMAILChanged();
            }
        }
        private global::System.String _PER_EMAIL;
        partial void OnPER_EMAILChanging(global::System.String value);
        partial void OnPER_EMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PER_VIGENCIA
        {
            get
            {
                return _PER_VIGENCIA;
            }
            set
            {
                OnPER_VIGENCIAChanging(value);
                ReportPropertyChanging("PER_VIGENCIA");
                _PER_VIGENCIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PER_VIGENCIA");
                OnPER_VIGENCIAChanged();
            }
        }
        private global::System.String _PER_VIGENCIA;
        partial void OnPER_VIGENCIAChanging(global::System.String value);
        partial void OnPER_VIGENCIAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CES_USUARIO_FK_PER", "CES_USUARIO")]
        public EntityCollection<CES_USUARIO> CES_USUARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CES_USUARIO>("Model.CES_USUARIO_FK_PER", "CES_USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CES_USUARIO>("Model.CES_USUARIO_FK_PER", "CES_USUARIO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CES_TIPO_ADMIN_MED")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CES_TIPO_ADMIN_MED : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CES_TIPO_ADMIN_MED object.
        /// </summary>
        /// <param name="tIPO_ADM_ID">Initial value of the TIPO_ADM_ID property.</param>
        /// <param name="tIPO_ADM_DESCRIPCION">Initial value of the TIPO_ADM_DESCRIPCION property.</param>
        /// <param name="tIPO_ADM_VIGENCIA">Initial value of the TIPO_ADM_VIGENCIA property.</param>
        public static CES_TIPO_ADMIN_MED CreateCES_TIPO_ADMIN_MED(global::System.Int16 tIPO_ADM_ID, global::System.String tIPO_ADM_DESCRIPCION, global::System.String tIPO_ADM_VIGENCIA)
        {
            CES_TIPO_ADMIN_MED cES_TIPO_ADMIN_MED = new CES_TIPO_ADMIN_MED();
            cES_TIPO_ADMIN_MED.TIPO_ADM_ID = tIPO_ADM_ID;
            cES_TIPO_ADMIN_MED.TIPO_ADM_DESCRIPCION = tIPO_ADM_DESCRIPCION;
            cES_TIPO_ADMIN_MED.TIPO_ADM_VIGENCIA = tIPO_ADM_VIGENCIA;
            return cES_TIPO_ADMIN_MED;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TIPO_ADM_ID
        {
            get
            {
                return _TIPO_ADM_ID;
            }
            set
            {
                if (_TIPO_ADM_ID != value)
                {
                    OnTIPO_ADM_IDChanging(value);
                    ReportPropertyChanging("TIPO_ADM_ID");
                    _TIPO_ADM_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TIPO_ADM_ID");
                    OnTIPO_ADM_IDChanged();
                }
            }
        }
        private global::System.Int16 _TIPO_ADM_ID;
        partial void OnTIPO_ADM_IDChanging(global::System.Int16 value);
        partial void OnTIPO_ADM_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO_ADM_DESCRIPCION
        {
            get
            {
                return _TIPO_ADM_DESCRIPCION;
            }
            set
            {
                OnTIPO_ADM_DESCRIPCIONChanging(value);
                ReportPropertyChanging("TIPO_ADM_DESCRIPCION");
                _TIPO_ADM_DESCRIPCION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIPO_ADM_DESCRIPCION");
                OnTIPO_ADM_DESCRIPCIONChanged();
            }
        }
        private global::System.String _TIPO_ADM_DESCRIPCION;
        partial void OnTIPO_ADM_DESCRIPCIONChanging(global::System.String value);
        partial void OnTIPO_ADM_DESCRIPCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO_ADM_VIGENCIA
        {
            get
            {
                return _TIPO_ADM_VIGENCIA;
            }
            set
            {
                OnTIPO_ADM_VIGENCIAChanging(value);
                ReportPropertyChanging("TIPO_ADM_VIGENCIA");
                _TIPO_ADM_VIGENCIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIPO_ADM_VIGENCIA");
                OnTIPO_ADM_VIGENCIAChanged();
            }
        }
        private global::System.String _TIPO_ADM_VIGENCIA;
        partial void OnTIPO_ADM_VIGENCIAChanging(global::System.String value);
        partial void OnTIPO_ADM_VIGENCIAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CES_MEDICAMENTO_FK_ADM", "CES_MEDICAMENTO")]
        public EntityCollection<CES_MEDICAMENTO> CES_MEDICAMENTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CES_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_ADM", "CES_MEDICAMENTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CES_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_ADM", "CES_MEDICAMENTO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CES_TIPO_MEDICAMENTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CES_TIPO_MEDICAMENTO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CES_TIPO_MEDICAMENTO object.
        /// </summary>
        /// <param name="tIPO_MED_ID">Initial value of the TIPO_MED_ID property.</param>
        /// <param name="tIPO_MED_DESCRIPCION">Initial value of the TIPO_MED_DESCRIPCION property.</param>
        /// <param name="tIPO_MED_VIGENCIA">Initial value of the TIPO_MED_VIGENCIA property.</param>
        public static CES_TIPO_MEDICAMENTO CreateCES_TIPO_MEDICAMENTO(global::System.Int16 tIPO_MED_ID, global::System.String tIPO_MED_DESCRIPCION, global::System.String tIPO_MED_VIGENCIA)
        {
            CES_TIPO_MEDICAMENTO cES_TIPO_MEDICAMENTO = new CES_TIPO_MEDICAMENTO();
            cES_TIPO_MEDICAMENTO.TIPO_MED_ID = tIPO_MED_ID;
            cES_TIPO_MEDICAMENTO.TIPO_MED_DESCRIPCION = tIPO_MED_DESCRIPCION;
            cES_TIPO_MEDICAMENTO.TIPO_MED_VIGENCIA = tIPO_MED_VIGENCIA;
            return cES_TIPO_MEDICAMENTO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TIPO_MED_ID
        {
            get
            {
                return _TIPO_MED_ID;
            }
            set
            {
                if (_TIPO_MED_ID != value)
                {
                    OnTIPO_MED_IDChanging(value);
                    ReportPropertyChanging("TIPO_MED_ID");
                    _TIPO_MED_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TIPO_MED_ID");
                    OnTIPO_MED_IDChanged();
                }
            }
        }
        private global::System.Int16 _TIPO_MED_ID;
        partial void OnTIPO_MED_IDChanging(global::System.Int16 value);
        partial void OnTIPO_MED_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO_MED_DESCRIPCION
        {
            get
            {
                return _TIPO_MED_DESCRIPCION;
            }
            set
            {
                OnTIPO_MED_DESCRIPCIONChanging(value);
                ReportPropertyChanging("TIPO_MED_DESCRIPCION");
                _TIPO_MED_DESCRIPCION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIPO_MED_DESCRIPCION");
                OnTIPO_MED_DESCRIPCIONChanged();
            }
        }
        private global::System.String _TIPO_MED_DESCRIPCION;
        partial void OnTIPO_MED_DESCRIPCIONChanging(global::System.String value);
        partial void OnTIPO_MED_DESCRIPCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO_MED_VIGENCIA
        {
            get
            {
                return _TIPO_MED_VIGENCIA;
            }
            set
            {
                OnTIPO_MED_VIGENCIAChanging(value);
                ReportPropertyChanging("TIPO_MED_VIGENCIA");
                _TIPO_MED_VIGENCIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIPO_MED_VIGENCIA");
                OnTIPO_MED_VIGENCIAChanged();
            }
        }
        private global::System.String _TIPO_MED_VIGENCIA;
        partial void OnTIPO_MED_VIGENCIAChanging(global::System.String value);
        partial void OnTIPO_MED_VIGENCIAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CES_MEDICAMENTO_FK_TIPO_MED", "CES_MEDICAMENTO")]
        public EntityCollection<CES_MEDICAMENTO> CES_MEDICAMENTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CES_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_TIPO_MED", "CES_MEDICAMENTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CES_MEDICAMENTO>("Model.CES_MEDICAMENTO_FK_TIPO_MED", "CES_MEDICAMENTO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CES_TIPO_USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CES_TIPO_USUARIO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CES_TIPO_USUARIO object.
        /// </summary>
        /// <param name="tIPO_USUARIO_ID">Initial value of the TIPO_USUARIO_ID property.</param>
        /// <param name="tIPO_USUARIO_DESCRIPCION">Initial value of the TIPO_USUARIO_DESCRIPCION property.</param>
        /// <param name="tIPO_USUARIO_VIGENCIA">Initial value of the TIPO_USUARIO_VIGENCIA property.</param>
        public static CES_TIPO_USUARIO CreateCES_TIPO_USUARIO(global::System.Int16 tIPO_USUARIO_ID, global::System.String tIPO_USUARIO_DESCRIPCION, global::System.String tIPO_USUARIO_VIGENCIA)
        {
            CES_TIPO_USUARIO cES_TIPO_USUARIO = new CES_TIPO_USUARIO();
            cES_TIPO_USUARIO.TIPO_USUARIO_ID = tIPO_USUARIO_ID;
            cES_TIPO_USUARIO.TIPO_USUARIO_DESCRIPCION = tIPO_USUARIO_DESCRIPCION;
            cES_TIPO_USUARIO.TIPO_USUARIO_VIGENCIA = tIPO_USUARIO_VIGENCIA;
            return cES_TIPO_USUARIO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TIPO_USUARIO_ID
        {
            get
            {
                return _TIPO_USUARIO_ID;
            }
            set
            {
                if (_TIPO_USUARIO_ID != value)
                {
                    OnTIPO_USUARIO_IDChanging(value);
                    ReportPropertyChanging("TIPO_USUARIO_ID");
                    _TIPO_USUARIO_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TIPO_USUARIO_ID");
                    OnTIPO_USUARIO_IDChanged();
                }
            }
        }
        private global::System.Int16 _TIPO_USUARIO_ID;
        partial void OnTIPO_USUARIO_IDChanging(global::System.Int16 value);
        partial void OnTIPO_USUARIO_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO_USUARIO_DESCRIPCION
        {
            get
            {
                return _TIPO_USUARIO_DESCRIPCION;
            }
            set
            {
                OnTIPO_USUARIO_DESCRIPCIONChanging(value);
                ReportPropertyChanging("TIPO_USUARIO_DESCRIPCION");
                _TIPO_USUARIO_DESCRIPCION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIPO_USUARIO_DESCRIPCION");
                OnTIPO_USUARIO_DESCRIPCIONChanged();
            }
        }
        private global::System.String _TIPO_USUARIO_DESCRIPCION;
        partial void OnTIPO_USUARIO_DESCRIPCIONChanging(global::System.String value);
        partial void OnTIPO_USUARIO_DESCRIPCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO_USUARIO_VIGENCIA
        {
            get
            {
                return _TIPO_USUARIO_VIGENCIA;
            }
            set
            {
                OnTIPO_USUARIO_VIGENCIAChanging(value);
                ReportPropertyChanging("TIPO_USUARIO_VIGENCIA");
                _TIPO_USUARIO_VIGENCIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIPO_USUARIO_VIGENCIA");
                OnTIPO_USUARIO_VIGENCIAChanged();
            }
        }
        private global::System.String _TIPO_USUARIO_VIGENCIA;
        partial void OnTIPO_USUARIO_VIGENCIAChanging(global::System.String value);
        partial void OnTIPO_USUARIO_VIGENCIAChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CES_USUARIO_FK_TIPO_USU", "CES_USUARIO")]
        public EntityCollection<CES_USUARIO> CES_USUARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CES_USUARIO>("Model.CES_USUARIO_FK_TIPO_USU", "CES_USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CES_USUARIO>("Model.CES_USUARIO_FK_TIPO_USU", "CES_USUARIO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CES_USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CES_USUARIO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CES_USUARIO object.
        /// </summary>
        /// <param name="uSU_ID">Initial value of the USU_ID property.</param>
        /// <param name="uSU_NOMBRE_USUARIO">Initial value of the USU_NOMBRE_USUARIO property.</param>
        /// <param name="uSU_CLAVE">Initial value of the USU_CLAVE property.</param>
        /// <param name="uSU_VIGENCIA">Initial value of the USU_VIGENCIA property.</param>
        /// <param name="pER_RUT">Initial value of the PER_RUT property.</param>
        /// <param name="tIPO_USUARIO_ID">Initial value of the TIPO_USUARIO_ID property.</param>
        public static CES_USUARIO CreateCES_USUARIO(global::System.Int16 uSU_ID, global::System.String uSU_NOMBRE_USUARIO, global::System.String uSU_CLAVE, global::System.String uSU_VIGENCIA, global::System.Int32 pER_RUT, global::System.Int16 tIPO_USUARIO_ID)
        {
            CES_USUARIO cES_USUARIO = new CES_USUARIO();
            cES_USUARIO.USU_ID = uSU_ID;
            cES_USUARIO.USU_NOMBRE_USUARIO = uSU_NOMBRE_USUARIO;
            cES_USUARIO.USU_CLAVE = uSU_CLAVE;
            cES_USUARIO.USU_VIGENCIA = uSU_VIGENCIA;
            cES_USUARIO.PER_RUT = pER_RUT;
            cES_USUARIO.TIPO_USUARIO_ID = tIPO_USUARIO_ID;
            return cES_USUARIO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 USU_ID
        {
            get
            {
                return _USU_ID;
            }
            set
            {
                if (_USU_ID != value)
                {
                    OnUSU_IDChanging(value);
                    ReportPropertyChanging("USU_ID");
                    _USU_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("USU_ID");
                    OnUSU_IDChanged();
                }
            }
        }
        private global::System.Int16 _USU_ID;
        partial void OnUSU_IDChanging(global::System.Int16 value);
        partial void OnUSU_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_NOMBRE_USUARIO
        {
            get
            {
                return _USU_NOMBRE_USUARIO;
            }
            set
            {
                OnUSU_NOMBRE_USUARIOChanging(value);
                ReportPropertyChanging("USU_NOMBRE_USUARIO");
                _USU_NOMBRE_USUARIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_NOMBRE_USUARIO");
                OnUSU_NOMBRE_USUARIOChanged();
            }
        }
        private global::System.String _USU_NOMBRE_USUARIO;
        partial void OnUSU_NOMBRE_USUARIOChanging(global::System.String value);
        partial void OnUSU_NOMBRE_USUARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_CLAVE
        {
            get
            {
                return _USU_CLAVE;
            }
            set
            {
                OnUSU_CLAVEChanging(value);
                ReportPropertyChanging("USU_CLAVE");
                _USU_CLAVE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_CLAVE");
                OnUSU_CLAVEChanged();
            }
        }
        private global::System.String _USU_CLAVE;
        partial void OnUSU_CLAVEChanging(global::System.String value);
        partial void OnUSU_CLAVEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USU_VIGENCIA
        {
            get
            {
                return _USU_VIGENCIA;
            }
            set
            {
                OnUSU_VIGENCIAChanging(value);
                ReportPropertyChanging("USU_VIGENCIA");
                _USU_VIGENCIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USU_VIGENCIA");
                OnUSU_VIGENCIAChanged();
            }
        }
        private global::System.String _USU_VIGENCIA;
        partial void OnUSU_VIGENCIAChanging(global::System.String value);
        partial void OnUSU_VIGENCIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PER_RUT
        {
            get
            {
                return _PER_RUT;
            }
            set
            {
                OnPER_RUTChanging(value);
                ReportPropertyChanging("PER_RUT");
                _PER_RUT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PER_RUT");
                OnPER_RUTChanged();
            }
        }
        private global::System.Int32 _PER_RUT;
        partial void OnPER_RUTChanging(global::System.Int32 value);
        partial void OnPER_RUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TIPO_USUARIO_ID
        {
            get
            {
                return _TIPO_USUARIO_ID;
            }
            set
            {
                OnTIPO_USUARIO_IDChanging(value);
                ReportPropertyChanging("TIPO_USUARIO_ID");
                _TIPO_USUARIO_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TIPO_USUARIO_ID");
                OnTIPO_USUARIO_IDChanged();
            }
        }
        private global::System.Int16 _TIPO_USUARIO_ID;
        partial void OnTIPO_USUARIO_IDChanging(global::System.Int16 value);
        partial void OnTIPO_USUARIO_IDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CES_USUARIO_FK_PER", "CES_PERSONA")]
        public CES_PERSONA CES_PERSONA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_PERSONA>("Model.CES_USUARIO_FK_PER", "CES_PERSONA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_PERSONA>("Model.CES_USUARIO_FK_PER", "CES_PERSONA").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CES_PERSONA> CES_PERSONAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_PERSONA>("Model.CES_USUARIO_FK_PER", "CES_PERSONA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CES_PERSONA>("Model.CES_USUARIO_FK_PER", "CES_PERSONA", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CES_USUARIO_FK_TIPO_USU", "CES_TIPO_USUARIO")]
        public CES_TIPO_USUARIO CES_TIPO_USUARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_TIPO_USUARIO>("Model.CES_USUARIO_FK_TIPO_USU", "CES_TIPO_USUARIO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_TIPO_USUARIO>("Model.CES_USUARIO_FK_TIPO_USU", "CES_TIPO_USUARIO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CES_TIPO_USUARIO> CES_TIPO_USUARIOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CES_TIPO_USUARIO>("Model.CES_USUARIO_FK_TIPO_USU", "CES_TIPO_USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CES_TIPO_USUARIO>("Model.CES_USUARIO_FK_TIPO_USU", "CES_TIPO_USUARIO", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
